services:
  nest:
    build:
      context: .
      dockerfile: docker/nest/dockerfile
    command: bun run start:dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync+restart
          path: package.json
          target: /app/package.json
        - action: sync+restart
          path: bun.lock
          target: /app/bun.lock

  mongo:
    build:
      context: .
      dockerfile: docker/mongo/dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    develop:
      watch:
        - action: rebuild
          path: docker/mongo/dockerfile

volumes:
  mongo_data:
